version: "3.3"
services:
  iotsw:
    container_name: digitalflightlog
    image: stephanflug/iotsw:V1
    privileged: true
    ports:
      - 1880:1880
      - 1883:1883
    restart: unless-stopped
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
    volumes:
      - /opt/digitalflugbuch/data:/data
      - /opt/digitalflugbuch/data/mqtt:/data/mqtt
      - /opt/digitalflugbuch/data/nodered:/data/nodered
      - /opt/digitalflugbuch/data/python3:/data/python3
networks: {}
